language: java
script: mvn test -B
notifications:
  slack:
    rooms:
      - secure: q7Asa1A3snmWnEqB5LkNrT7x2WecL1kPu/LH1JiZNTtpVV+aniqv6bTeFvNwZ6uTujYV0ppTH4DL5JhkI2W2ErbAe/0E0zKkR4LTRyV2Vsgz71z3W63aWNzPjcvFB3JAdtVqWivHklFw7Vu4Bn586G9hRM9WEQIatPexohQJakl2ffAIht0Rej0Muy7Ag3XORLyqkknmZuTkLTvM+RtW/ptEjitzIIZT0SDH3l0pj5+V88WAut08e/tkc3aBjItWhLwsGfUOQ1BRLuYfrAUIhIRzkOfmhMhfUtuT23p7MIv4UhUkAMFwcEJ3AIWM2e1Xh1EzPKC57AGbt5NxphIXhO8Ptz7/TPKFPrz/X5iTy6Hylygd5dEXNxuygjh90ave33GAxUw3wEQtsHkILIOKQJeVrq/tCVll7A/SYKV6j09hJoTuNZJCFcx5815KGF1lR0YQeZIJyWby6IKjtmeioAEX+EKFLm/sN2ivZrvRHw7mjjmBYYSGISvd/HfDbKAkxS3KpXxSQjN00T5B/jeTpwLXOmYfJUAHiK9RepRH50JSMYDIyc30sAwN6E4HKDp9ZQplEPCVic2vF9qBvipusb7aSHKoTMSwNCNpi+lMP8eeMvYl+7LfDqnu1zAHneH6cp91zg1J/CEVL+bmTiv4mZOEIBCcZodvUiHu4FKux1A=
